name: "Coverage Report"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: write

jobs:
  code_coverage:
    name: "Code coverage"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: go test -v ./...

    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        report: true
        chart: true
        amend: true
      continue-on-error: true